---
title: Introduction to FAIR
---

:::::::::::::::::::::::::::::::::::::: questions 

- What is FAIR?
- Why should I care (about being FAIR)?
- Why early planning around FAIR will benefit your project later on?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand the basic premise behind the FAIR Principles
- Know why it is useful and important to apply these principle to my work
- Understand that working towards FAIR outputs should occur throughout a project lifecycle

::::::::::::::::::::::::::::::::::::::::::::::::


## What is FAIR

If you've gone to any of the other session in the FAIR4RS course then hopefully you'll be familiar with this. However, it's always good to know why we're all here so we'll quickly go over the main points around FAIR.

###Not just software, or research

Of course FAIR isn't just for your code and software, and not just something in research. They can be applied to all outputs from all types of projects.

It stands for Findable, Accessible, Interoperable, and Reusable, and were developed in 2016. The main element of FAIR however resides in the 'R', with the 'FAI' being elements that help outputs to be more reusable, which is the ultimate aim.

:::::::::::::::::::::::::::::::::::::::::::::::: remember
FAIR (in research), covers practically everything that isn't the final journal output, which includes, both qualitative and quantitative data, data collection forms, photos, scans, maps, coding schemes, interview topic guides, sound recordings, lab notebooks and more. It can be both the raw, processed, or analysied data.
::::::::::::::::::::::::::::::::::::::::::::::::


###Why should I care (about being FAIR)?





::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::
